x-app: &default-app
  logging:
    driver: 'json-file'
    options:
      max-size: '500k'
      max-file: '5'
  restart: 'unless-stopped'
  stop_grace_period: '3s'

services:
  nginx:
    <<: *default-app
    container_name: ${DOCKER_SYMFONY_PROJECT_NAME}_nginx
    build:
      context: ./docker/build/nginx
    volumes:
      - ./docker/mount/app:/var/www/html
      - ./docker/mount/config/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/mount/logs/nginx/access_log:/var/log/nginx/access_log
      - ./docker/mount/logs/nginx/error_log:/var/log/nginx/error_log
    ports:
      - "${DOCKER_SYMFONY_HOST_PORT_HTTP}:80"
      - "${DOCKER_SYMFONY_HOST_PORT_HTTPS}:443"
    depends_on:
      - php_fpm
  php_fpm:
    <<: *default-app
    container_name: ${DOCKER_SYMFONY_PROJECT_NAME}_php_fpm
    build:
      context: ./docker/build/php-fpm
      args:
        TIMEZONE: ${DOCKER_SYMFONY_TIMEZONE}
    volumes:
      - type: bind
        source: ./docker/mount/app
        target: /var/www/html
    depends_on:
      - mariadb
  mariadb:
    <<: *default-app
    container_name: ${DOCKER_SYMFONY_PROJECT_NAME}_mariadb
    build:
      context: ./docker/build/mariadb
    environment:
      MARIADB_DATABASE: ${DOCKER_SYMFONY_DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DOCKER_SYMFONY_DB_ROOT_PASSWORD}
      MARIADB_USER: ${DOCKER_SYMFONY_DB_USER_NAME}
      MARIADB_PASSWORD: ${DOCKER_SYMFONY_DB_USER_PASSWORD}
    volumes:
      - ./docker/mount/config/mariadb/etc/mysql/mariadb.conf.d:/etc/mysql/mariadb.conf.d
      - ./docker/mount/data/mariadb/dbfiles:/var/lib/mysql
      - ./docker/mount/data/mariadb/initdb:/docker-entrypoint-initdb.d
      - ./docker/mount/logs/mariadb:/var/log/mysql
